const tropes = {
    "The Hero's Journey": 1,
    "Chosen One": 2,
    "Mentor Archetype": 3,
    "Comic Relief": 4,
    "Femme Fatale": 5,
    "Anti-Hero": 6,
    "Love Triangle": 7,
    "Tragic Hero": 8,
    "The Sidekick": 9,
    "The Big Bad": 10,
    "The Dragon": 11,
    "The Damsel in Distress": 12,
    "The Wise Old Sage": 13,
    "The Lancer": 14,
    "The Plucky Comic Relief": 15,
    "The Rival": 16,
    "The Team Mom": 17,
    "The Team Dad": 18,
    "The Rebel": 19,
    "Fish Out of Water": 20,
    "The Gentle Giant": 21,
    "The Smart Guy": 22,
    "The Stoic": 23,
    "The Trickster": 24,
    "The Villain with a Heart of Gold": 25,
    "The Dark Lord": 26,
    "The Mad Scientist": 27,
    "The Farm Boy": 28,
    "The Innocent Bystander": 29,
    "The Doppelganger": 30,
    "The Shape-Shifter": 31,
    "The Secret Identity": 32,
    "The Masked Vigilante": 33,
    "The Knight in Shining Armor": 34,
    "The Noble Savage": 35,
    "The Old Master": 36,
    "The Star-Crossed Lovers": 37,
    "The Puppetmaster": 38,
    "The Evil Genius": 39,
    "The Unlikely Hero": 40,
    "The Orphan": 41,
    "The Kid with the Leash": 42,
    "The Sibling Rivalry": 43,
    "The Overprotective Parent": 44,
    "The Guilt-Ridden Survivor": 45,
    "The Master of Disguise": 46,
    "The Dashing Rogue": 47,
    "The Gentleman Thief": 48,
    "The Unlikely Allies": 49,
    "The Nurturer": 50,
    "The Neat Freak": 51,
    "The Lovable Nerd": 52,
    "Forced To Watch": 53,
    "The Byronic Hero": 54,
    "The Reluctant Warrior": 55,
    "The Wounded Healer": 56,
    "The Amnesiac": 57,
    "The Determinator": 58,
    "The Jaded Cynic": 59,
    "The Fallen Hero": 60,
    "The Manic Pixie Dream Girl": 61,
    "The Quirky Best Friend": 62,
    "The Proud Warrior": 63,
    "The Martyr": 64,
    "The Quiet One": 65,
    "The Bratty Sibling": 66,
    "The Impulsive Adventurer": 67,
    "The Hapless Hero": 68,
    "The Cowardly Lion": 69,
    "The Cloud Cuckoolander": 70,
    "The Action Girl": 71,
    "The Naïve Newcomer": 72,
    "The Boisterous Bruiser": 73,
    "The Superhero": 74,
    "The Robot Buddy": 75,
    "The Distant Dystopia": 76,
    "The Friendly Neighborhood Vampire": 77,
    "The Supernatural Detective": 78,
    "The Eldritch Abomination": 79,
    "The Magical Girl": 80,
    "The Girl Next Door": 81,
    "The Knight in Sour Armor": 82,
    "The Chivalrous Pervert": 83,
    "The Last of Their Kind": 84,
    "The Sassy Sidekick": 85,
    "The Blind Seer": 86,
    "The Child Prodigy": 87,
    "The Time Traveler": 88,
    "The Sole Survivor": 89,
    "The Evil Twin": 90,
    "The Femme Fatale Spy": 91,
    "The Alien Visitor": 92,
    "The Space Marine": 93,
    "The Ancient Astronaut": 94,
    "The Human Alien": 95,
    "The Final Girl": 96,
    "The Zombie Apocalypse": 97,
    "The Creepy Child": 98,
    "The Monster in the Closet": 99,
    "The Town with a Dark Secret": 100,
    "The Unreliable Narrator": 101,
    "The False Friend": 102,
    "The Hardboiled Detective": 103,
    "The Gentleman Adventurer": 104,
    "The Secret Keeper": 105,
    "The Rebellious Princess": 106,
    "The Hidden Villain": 107,
    "The Prophecy": 108,
    "The Red Herring": 109,
    "The Mentor's Death": 110,
    "The Power of Friendship": 111,
    "The Cursed Item": 112,
    "The MacGuffin": 113,
    "The Enigmatic Empowering Entity": 114,
    "The Unexpected Inheritance": 115,
    "The Evil Empire": 116,
    "The Utopia Justifies the Means": 117,
    "The Artifact of Doom": 118,
    "The Power of Love": 119,
    "The Ragtag Bunch of Misfits": 120,
    "The Childhood Friend Romance": 121,
    "The Lost Technology": 122,
    "The Forbidden Zone": 123,
    "The Mysterious Stranger": 124,
    "The Obnoxious In-Laws": 125,
    "The Vengeful Ghost": 126,
    "The Roaring Rampage of Revenge": 127,
    "The Sacrificial Lamb": 128,
    "The Secret Society": 129,
    "The Whodunit": 130,
    "The Desperate Struggle for Survival": 131,
    "The City Noir": 132,
    "The Dream Within a Dream": 133,
    "The Xanatos Gambit": 134,
    "The Ominous Message from the Future": 135,
    "The Apocalyptic Log": 136,
    "The Multiverse": 137,
    "The Ancient Conspiracy": 138,
    "The Evil Matriarch": 139,
    "The Reluctant Ruler": 140,
    "The Deadpan Snarker": 141,
    "The Unstoppable Rage": 142,
    "The Five-Man Band": 143,
    "The Superpowered Alter Ego": 144,
    "The Cynical Mentor": 145,
    "The Muggle in a Magical World": 146,
    "The Clingy Jealous Girl": 147,
    "The Ingenue": 148,
    "The Beauty and the Beast": 149,
    "The Threshold Guardians": 150,
    "The Test of Character": 151,
    "The Haunted House": 152,
    "The Closed Circle": 153,
    "The Immortality Seeker": 154,
    "The Fugitive Arc": 155,
    "The Great Offscreen War": 156,
    "The Gentleman and the Scoundrel": 157,
    "The Cult": 158,
    "The Serendipitous Survival": 159,
    "The Love Redeems": 160,
    "The Lone Wolf": 161,
    "The Faux Affably Evil": 162,
    "The Parental Substitute": 163,
    "The Non-Human Sidekick": 164,
    "The Cosmic Horror Story": 165,
    "The Ghostly Goals": 166,
    "The Reluctant Monster": 167,
    "The Dying Race": 168,
    "The False Utopia": 169,
    "The Secret War": 170,
    "The Masquerade": 171,
    "The Amoral Attorney": 172,
    "The Femme Fatale Bounty Hunter": 173,
    "The Time Loop": 174,
    "The Planetary Romance": 175,
    "The Mad Artist": 176,
    "The Dystopian Society": 177,
    "The Eldritch Location": 178,
    "The Fair Folk": 179,
    "The Gadgeteer Genius": 180,
    "The Loveable Rogue": 181,
    "The Princess in Rags": 182,
    "The Drunken Master": 183,
    "The Cassandra Truth": 184,
    "The Last Stand": 185,
    "The Great Escape": 186,
    "The Caper": 187,
    "The Vampiric Draining": 188,
    "The Sympathetic Inspector Antagonist": 189,
    "The Righteous Avenger": 190,
    "The Pirates Who Don't Do Anything": 191,
    "The Magical Land": 192,
    "The Disguised in Drag": 193,
    "The Sealed Evil in a Can": 194,
    "The Loophole Abuse": 195,
    "The Faux Action Girl": 196,
    "The Lovable Traitor": 197,
    "The Island": 198,
      "The Evil Sorcerer": 199,
    "The Gentleman Detective": 200,
    "The Oracular Head": 201,
    "The Street Urchin": 202,
    "The Magical Nanny": 203,
    "The Monster Progenitor": 204,
    "The Great Detective": 205,
    "The Rags to Riches": 206,
    "The Evil Chancellor": 207,
    "The Reincarnation Romance": 208,
    "The Absent-Minded Professor": 209,
    "The Mad Oracle": 210,
    "The Portal Fantasy": 211,
    "The Twin Switch": 212,
    "The Artificial Intelligence": 213,
    "The Royal Bastard": 214,
    "The Village Idiot": 215,
    "The Bounty Hunter": 216,
    "The Ghost Hunter": 217,
    "The Military Maverick": 218,
    "The Disappeared Dad": 219,
    "The Hidden Elf Village": 220,
    "The Heroic Sacrifice": 221,
    "The Living Legend": 222,
    "The Mind Screw": 223,
    "The Ordinary High-School Student": 224,
    "The Pre-Mortem One-Liner": 225,
    "The Science Hero": 226,
    "The Time Police": 227,
    "The Deal with the Devil": 228,
    "The Unresolved Sexual Tension": 229,
    "The Dystopia Is Hard": 230,
    "The Badass Normal": 231,
    "The Tomboy Princess": 232,
    "The Devil in Plain Sight": 233,
    "The Lady of War": 234,
    "The Urban Fantasy": 235,
    "The Mistaken for Gay": 236,
    "The Mock Millionaire": 237,
    "The Vampire Detective": 238,
    "The Wacky Parent, Serious Child": 239,
    "The Wolf in Sheep's Clothing": 240,
    "The Loveable Alpha Bitch": 241,
    "The Tsundere": 242,
    "The Yandere": 243,
    "The Damsel out of Distress": 244,
    "The Contemplate Our Navels": 245,
    "The Forbidden Romance": 246,
    "The Handsome Lech": 247,
    "The Retired Badass": 248,
  };
  
  const genreMapping = {
    "Action": 1,
    "Adventure": 2,
    "Comedy": 3,
    "Crime": 4,
    "Drama": 5,
    "Fantasy": 6,
    "Historical": 7,
    "Horror": 8,
    "Mystery": 9,
    "Romance": 10,
    "Sci-Fi": 11,
    "Thriller": 12,
    "Western": 13,
    "Biography": 14,
    "Musical": 15,
    "Superhero": 16,
    "Heist": 17,
    "War": 18,
    "Post-Apocalyptic": 19,
    "Spy": 20,
    "Gothic": 21,
    "Urban Fantasy": 22,
    "Sword and Sorcery": 23,
    "Hard Science Fiction": 24,
    "Soft Science Fiction": 25,
    "Cyberpunk": 26,
    "Steampunk": 27,
    "Dystopian": 28,
    "Utopian": 29,
    "Space Opera": 30,
    "Time Travel": 31,
    "Alternate History": 32,
    "Political": 33,
    "Psychological": 34,
    "Fairy Tale": 35,
    "Mythology": 36,
    "Paranormal": 37,
    "Noir": 38,
    "Pulp": 39,
    "Satire": 40,
    "Tragedy": 41,
    "Epic": 42,
    "Magical Realism": 43,
    "Surrealism": 44,
    "Bildungsroman": 45,
    "Metafiction": 46,
    "Neo-noir": 47,
    "Romantic Comedy": 48,
    "Courtroom": 49,
    "Erotica": 50,
    "Dark Fantasy": 51,
    "High Fantasy": 52,
    "Low Fantasy": 53,
    "Paranormal Romance": 54,
    "New Weird": 55,
    "Slipstream": 56,
    "Experimental": 57,
    "Absurdist": 58,
    "New Adult": 59,
    "Chick Lit": 60,
    "Legal Thriller": 61,
    "Medical Thriller": 62,
    "Techno-Thriller": 63,
    "Cozy Mystery": 64,
    "Police Procedural": 65,
    "Historical Romance": 66,
    "Regency Romance": 67,
    "Science Fantasy": 68,
    "New Wave Science Fiction": 69,
    "Solarpunk": 70
  };
  
  
  const newTropes = [
    "Secret Identity",
    "Fish out of Water",
    "Time Travel",
    "Road Trip",
    "Villain Protagonist",
    "Coming of Age",
    "Body Swap",
    "Redemption Quest",
    "Battle Royale",
    "Dystopian Future",
    "Forbidden Love",
    "Friends to Lovers",
    "Mistaken Identity",
    "Survival Horror",
    "Underdog Story",
    "Rags to Riches",
    "Riches to Rags",
    "Hero's Journey",
    "Found Family",
    "Quest for MacGuffin",
    "Unrequited Love",
    "Twist Ending",
    "Love at First Sight",
    "Redemption Equals Death",
    "High School AU",
    "Body Horror",
    "Black Comedy",
    "Reality Warper",
    "Star-Crossed Lovers",
    "Mind Control",
    "Post-Apocalyptic World",
    "Deal with the Devil",
    "Fish out of Temporal Water",
    "Character Study",
    "Amnesia",
    "Battle Couple",
    "Reformed, but Not Tamed",
    "Eldritch Abomination",
    "Evil Twin",
    "False Friend",
    "Ghost Story",
    "Hard-Boiled Detective",
    "Immortality Seeker",
    "It Was All a Dream",
    "Journey to the Centre of the Mind",
    "The Last Dance",
    "The Mentor",
    "Not What It Looks Like",
    "Ordinary High-School Student",
    "Parental Abandonment",
    "Quest for Identity",
    "Roadside Hotel",
    "Screwball Comedy",
    "Starfish Aliens",
    "Troubled Backstory Flashback",
    "Two-Faced",
    "Childhood Sweethearts",
    "Opposites Attract",
    "Love-Hate Relationship",
    "Workplace Romance",
    "Slow Burn",
    "Uptown Girl",
    "Friends with Benefits",
    "May-December Romance",
    "Second Chance Romance",
    "Love Triangle with a Twist",
    "Love Dodecahedron",
    "In Love with the Nanny",
    "Enemistry",
    "First Love",
    "Masquerade Ball",
    "Royal Romance",
    "Sports Romance",
    "Internet Relationship",
    "Non-Romantic Life-Partner",
    "Love Potion",
    "The Chosen Zero",
    "The Gentleman Snarker",
    "The Unwitting Pawn",
    "The Artful Dodger",
    "The Cursed with Awesome",
    "The Deadpan Snarker",
    "The Defrosting Ice Queen",
    "The Dying Declaration of Love",
    "The Eccentric Mentor",
    "The Femme Fatale",
    "The Flaw Exploitation",
    "The Gambit Roulette",
    "The Haunted Heroine",
    "The Humble Hero",
    "The Insufferable Genius",
    "The Jerk with a Heart of Gold",
    "The Kid Sidekick",
    "The Lady of War",
    "The Magnificent Bastard",
    "The Master of Illusion",
    "The Nightmare Fuel Station Attendant",
    "The Omniscient Morality License",
    "The Peerless Love Interest",
    "The Quippy Sidekick",
    "The Reluctant Retiree",
    "The Reveal",
    "The Secret Test of Character",
    "The Shipper on Deck",
    "The Snark Knight",
    "The Stoic Woobie",
    "The Tragic Villain",
    "The Unfettered",
    "The Villainous Crush",
    "The Warrior Poet",
    "The Wounded Gazelle Gambit",
    "The Xanatos Speed Chess",
    "The Yin-Yang Bomb",
    "The You Shall Not Pass",
    "The Zero-Approval Gambit",
    "The Zany Scheme",
    "The Zombie Advocate",
    "The Self-Fulfilling Prophecy",
    "The Skeletons in the Coat Closet",
    "The Struggling Single Mother",
    "The Suspiciously Specific Denial",
    "The Token Evil Teammate",
    "The Training Montage",
    "The Unflappable Stoic",
    "The Vigilante Man",
    "The Walking the Earth",
    "The Wham Line"
  ];
  
  const genres = {
    "Action": 1,
    "Adventure": 2,
    "Comedy": 3,
    "Crime": 4,
    "Drama": 5,
    "Fantasy": 6,
    "Historical": 7,
    "Horror": 8,
    "Mystery": 9,
    "Romance": 10,
    "Sci-Fi": 11,
    "Thriller": 12,
    "Western": 13,
    "Biography": 14,
    "Musical": 15,
    "Superhero": 16,
    "Heist": 17,
    "War": 18,
    "Post-Apocalyptic": 19,
    "Spy": 20,
    "Gothic": 21,
    "Urban Fantasy": 22,
    "Sword and Sorcery": 23,
    "Hard Science Fiction": 24,
    "Soft Science Fiction": 25,
    "Cyberpunk": 26,
    "Steampunk": 27,
    "Dystopian": 28,
    "Utopian": 29,
    "Space Opera": 30,
    "Time Travel": 31,
    "Alternate History": 32,
    "Political": 33,
    "Psychological": 34,
    "Fairy Tale": 35,
    "Mythology": 36,
    "Paranormal": 37,
    "Noir": 38,
    "Pulp": 39,
    "Satire": 40,
    "Tragedy": 41,
    "Epic": 42,
    "Magical Realism": 43,
    "Surrealism": 44,
    "Bildungsroman": 45,
    "Metafiction": 46,
    "Neo-noir": 47,
    "Romantic Comedy": 48,
    "Courtroom": 49,
    "Erotica": 50,
    "Dark Fantasy": 51,
    "High Fantasy": 52,
    "Low Fantasy": 53,
    "Paranormal Romance": 54,
    "New Weird": 55,
    "Slipstream": 56,
    "Experimental": 57,
    "Absurdist": 58,
    "New Adult": 59,
    "Chick Lit": 60,
    "Legal Thriller": 61,
    "Medical Thriller": 62,
    "Techno-Thriller": 63,
    "Cozy Mystery": 64,
    "Police Procedural": 65,
    "Historical Romance": 66,
    "Regency Romance": 67,
    "Science Fantasy": 68,
    "New Wave Science Fiction": 69,
    "Solarpunk": 70,
    "Space Western": 71,
    "Sports Drama": 72,
    "Environmental Fiction": 73,
    "Philosophical Fiction": 74,
    "Coming-of-Age": 75,
    "Mythic Fiction": 76,
    "Postmodern Literature": 77,
    "Supernatural Thriller": 78,
    "Urban Legend": 79,
    "Campus Novel": 80,
    "Detective Fiction": 81,
    "Epistolary Novel": 82,
    "Family Saga": 83,
    "Feminist Fiction": 84,
    "Ghost Story": 85,
    "Hardboiled Fiction": 86,
    "Inspirational Fiction": 87,
    "Invasion Literature": 88,
    "Kitchen Sink Realism": 89,
    "Locked Room Mystery": 90,
    "Martial Arts": 91,
    "Mashup": 92,
    "Military Fiction": 93,
    "Nature Writing": 94,
    "Occult Fiction": 95,
    "Picaresque": 96,
    "Planetary Romance": 97,
    "Postcyberpunk": 98,
    "Psychological Thriller": 99,
    "Religious Fiction": 100,
    "Robinsonade": 101,
    "Romantic Suspense": 102,
    "Sea Story": 103,
    "Serial Killer Fiction": 104,
    "Slice of Life": 105,
    "Southern Gothic": 106,
    "Space Exploration": 107,
    "Splatterpunk": 108,
    "Spy Fiction": 109,
    "Superhero Fiction": 110,
    "Swashbuckler": 111,
    "Sword and Planet": 112,
    "Sword and Sandal": 113,
    "Tall Tale": 114,
    "Teen Drama": 115,
    "Treasure Hunt": 116,
    "Vampire Fiction": 117,
    "Weird West": 118,
    "Whodunit": 119,
    "Wuxia": 120,
    "Zombie Fiction": 121,
    "Dieselpunk": 122,
    "Folk Horror": 123,
    "Pirate Fiction": 124,
    "Alien Invasion": 125,
    "Apocalyptic Fiction": 126,
    "Bizarro Fiction": 127,
    "Cli-fi": 128,
    "Conspiracy Thriller": 129,
    "Cosmic Horror": 130,
    "Grimdark": 131,
    "Hardboiled Detective": 132,
    "Medical Drama": 133,
    "Mythopoeia": 134,
    "Prehistoric Fiction": 135,
    "Quest Narrative": 136,
    "Revenge Tragedy": 137,
    "Space Romance": 138,
    "Suburban Gothic": 139
  };
  
  const sizes = [
    'tiny',
    'small',
    'medium',
    'large',
    'huge',
    'gigantic',
    'colossal',
    'minuscule',
    'diminutive',
    'enormous',
    'titanic',
    'microscopic',
    'variable',
  ];
  
  const abilities = [
    'flight',
    'invisibility',
    'shape-shifting',
    'teleportation',
    'telepathy',
    'telekinesis',
    'regeneration',
    'fire-breathing',
    'water-breathing',
    'acidic touch',
    'electrokinesis',
    'cryokinesis',
    'pyrokinesis',
    'camouflage',
    'enhanced strength',
    'enhanced agility',
    'enhanced speed',
    'enhanced senses',
    'poisonous',
    'mimicry',
    'illusion casting',
    'time manipulation',
    'gravity manipulation',
    'phasing through objects',
    'clairvoyance',
    'control over plants',
    'control over animals',
    'control over weather',
    'energy absorption',
    'energy projection',
    'healing powers',
    'force field generation',
    'intangibility',
    'immortality',
    'dimensional travel',
    'growth/shrinking',
    'power nullification',
    'astral projection',
    'reality warping',
    'elemental control',
    'summoning',
    'necromancy',
    'technopathy',
    'self-duplication',
    'precognition',
    'probability manipulation',
    'sonic scream',
    'enhanced durability',
  ];
  
  const temperaments = [
    'friendly',
    'aggressive',
    'curious',
    'timid',
    'protective',
    'playful',
    'territorial',
    'intelligent',
    'loyal',
    'mischievous',
    'ferocious',
    'gentle',
    'solitary',
    'social',
    'fearful',
    'calm',
    'dominant',
    'submissive',
    'suspicious',
    'cunning',
    'lazy',
    'energetic',
    'docile',
    'migratory',
    'nurturing',
    'indifferent',
    'vengeful',
    'skittish',
    'devoted',
    'stubborn',
    'proud',
    'majestic',
  ];
  
  const bodyTypes = [
    'mammal',
    'reptile',
    'bird',
    'amphibian',
    'insect',
    'aquatic',
    'arachnid',
    'crustacean',
    'mollusk',
    'plant-based',
    'fungal',
    'elemental',
    'robotic',
    'ethereal',
    'shape-shifter',
    'hybrid',
    'avian-humanoid',
    'reptilian-humanoid',
    'mammalian-humanoid',
    'insectoid-humanoid',
    'draconic',
    'serpentine',
    'celestial',
    'demonic',
    'undead',
    'gaseous',
    'microscopic',
    'mechanical',
    'crystalline',
    'golem-like',
    'energy-based',
    'shadow',
    'chimeric',
  ];
  
  const habitats = [
    'forest',
    'jungle',
    'desert',
    'tundra',
    'grassland',
    'savanna',
    'mountain',
    'underground',
    'cave',
    'swamp',
    'marsh',
    'ocean',
    'coral reef',
    'coastal',
    'arctic',
    'volcanic',
    'river',
    'lake',
    'wetland',
    'island',
    'rainforest',
    'urban',
    'suburban',
    'farm',
    'garden',
    'ruins',
    'temple',
    'castle',
    'sky',
    'clouds',
    'plains',
    'steppe',
    'plateau',
    'glacier',
    'extraterrestrial',
    'interdimensional',
    'alternate reality',
    'magical realm',
    'underwater',
    'abyssal',
    'beach',
    'rocky shore',
    'deep sea',
    'seashore',
    'floating island',
    'magical forest',
  ];
  
  const behaviors = [
    'nocturnal',
    'diurnal',
    'crepuscular',
    'hibernating',
    'migrating',
    'burrowing',
    'hunting',
    'foraging',
    'grazing',
    'scavenging',
    'omnivorous',
    'carnivorous',
    'herbivorous',
    'insectivorous',
    'frugivorous',
    'piscivorous',
    'solitary',
    'social',
    'monogamous',
    'polygamous',
    'territorial',
    'nomadic',
    'sedentary',
    'brooding',
    'egg-laying',
    'live-bearing',
    'ambush predator',
    'pursuit predator',
    'filter feeder',
    'opportunistic feeder',
    'cooperative hunting',
    'aggressive mimicry',
    'camouflaging',
    'warning coloration',
    'mimicry',
    'tool use',
    'problem-solving',
    'play behavior',
    'nest building',
    'courtship display',
    'mate guarding',
    'altruistic behavior',
    'kin selection',
    'symbiosis',
    'parasitic',
    'mutualistic',
    'commensalistic',
  ];
  
  const colors = [
    "red",
    "blue",
    "green",
    "yellow",
    "orange",
    "purple",
    "brown",
    "black",
    "white",
    "gray",
    "pink",
    "violet",
    "indigo",
    "turquoise",
    "gold",
    "silver",
    "bronze",
    "teal",
    "maroon",
    "olive",
    "lime",
    "navy",
    "aquamarine",
    "magenta",
    "tan",
    "cyan",
    "lavender",
    "coral",
    "beige",
    "khaki"
  ];
  
  function randomElement(array) {
    return array[Math.floor(Math.random() * array.length)];
  };
  
  function generateCreature() {
    const bodyType = randomElement(bodyTypes);
    const size = randomElement(sizes);
    const ability = randomElement(abilities);
    const habitat = randomElement(habitats);
    const behavior = randomElement(behaviors);
    const color = randomElement(colors);
  
    // Return the formatted string
    return `You've generated a ${size} ${color} ${bodyType} creature that lives in the ${habitat}. Its main ability is ${ability} and its standard behavior is ${behavior}.`
    /*return `Body type: ${bodyType}\nSize: ${size}\nAbility: ${ability}\nHabitat: ${habitat}\nBehavior: ${behavior}\nColor: ${color}`;*/
  }
  
  
  let nextIndex = Object.keys(tropes).length + 1;
  
  for (const newTrope of newTropes) {
    if (!Object.keys(tropes).includes(newTrope)) {
      tropes[newTrope] = nextIndex;
      nextIndex++;
    }
  }
  
  console.log(tropes);
  
  function getRandomInt(min, max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }
  
  function getRandomGenre() {
    const randomNumber = getRandomInt(1, 70);
    for (const genre in genres) {
      if (genres[genre] === randomNumber) {
        return genre;
      }
    }
  }
  
  function getRandomTrope() {
    const randomNumber = getRandomInt(1, 198);
    for (const trope in tropes) {
      if (tropes[trope] === randomNumber) {
        return trope;
      }
    }
  }
  
  function combineTwoRandomTropes() {
    const trope1 = getRandomTrope();
    const trope2 = getRandomTrope();
    return trope1 + ' + ' + trope2;
  }
  
  function combineTwoRandomGenres() {
    const genre1 = getRandomGenre();
    const genre2 = getRandomGenre();
    return genre1 + ' + ' + genre2;
  }
  
  const form = document.getElementById('trope-form');
  const result = document.getElementById('result');
  
  document.getElementById('trope-btn').addEventListener('click', (e) => {
    e.preventDefault();
    result.textContent = combineTwoRandomTropes();
  });
  
  document.getElementById('genre-btn').addEventListener('click', (e) => {
    e.preventDefault();
    result.textContent = combineTwoRandomGenres();
  });
  
  document.getElementById('generateCreature').addEventListener('click', () => {
    const creature = generateCreature();
    result.textContent = creature;
  });
  
  const searchInput = document.getElementById('search');
  
  searchInput.addEventListener('input', (e) => {
    const searchTerm = e.target.value.toLowerCase();
  
    if (searchTerm) {
      const filteredTropes = Object.keys(tropes).filter(trope =>
        trope.toLowerCase().includes(searchTerm)
      );
  
      if (filteredTropes.length > 0) {
        result.innerHTML = filteredTropes.map(trope => `<li>${trope}</li>`).join('');
      } else {
        result.innerHTML = 'No matching tropes found.';
      }
    } else {
      result.innerHTML = '';
    }
  });
  